/**:
  ros__parameters:
    #  size_x is amr length and size_y is width
    size_x: 1.965
    size_y: 0.8
    # time interval (in seconds) within which not reporting amr's velocity will make it to be considered as stopped by others
    moving_speed_update_timeout: 60.0
    wheel_radius: 0.125
    wheelbase: 1.265 # distance between front and fork wheels
    fork_wheel_offset: 0.35 # distance from tip of fork to base_link
    max_speed: 1.5
