/**:
  local_costmap:
    local_costmap:
      ros__parameters:
        obstacle_layer:
          forward_lidar:
            obstacle_max_range: 2.5
            raytrace_max_range: 2.5

  global_costmap:
    global_costmap:
      ros__parameters:
        obstacle_layer:
          forward_lidar_clearing:
            obstacle_max_range: 2.5
          forward_lidar_marking:
            topic: /nonsense
