/**:
  local_costmap:
    local_costmap:
      ros__parameters:
        obstacle_layer:
          forward_lidar:
            obstacle_max_range: 2.5

  global_costmap:
    global_costmap:
      ros__parameters:
        obstacle_layer:
          forward_lidar:
            obstacle_max_range: 2.5

  amr_navigate_to_pose_amr_navigate_to_pose_rclcpp_node:
    ros__parameters:
      MonitorDrivingIntoPallet:
        threshold: 10000.0
