/**:
  local_costmap:
    local_costmap:
      ros__parameters:
        obstacle_layer:
          forward_lidar:
            obstacle_max_range: 3.0

  global_costmap:
    global_costmap:
      ros__parameters:
        obstacle_layer:
          forward_lidar:
            obstacle_max_range: 3.0