/**:
  local_costmap:
    local_costmap:
      ros__parameters:
        obstacle_layer:
          backward_lidar:
            obstacle_max_range: 2.5

  global_costmap:
    global_costmap:
      ros__parameters:
        obstacle_layer:
          backward_lidar_marking:
            obstacle_max_range: 2.5
