/**:
  realsense_right:
    realsense_right:
      ros__parameters:
        camera_name: "realsense_right"
        usb_port_id: "2-4.2"

  realsense_left:
    realsense_left:
      ros__parameters:
        camera_name: "realsense_left"
        usb_port_id: "2-4.3"
