# Parameters for the curtis controller
/**:
  f2a_parameters_manager:
    ros__parameters:
      f2a.lift_threshold_release: 10
      f2a.lift_scanner_threshold: 720
      f2a.lift_threshold_lift: 25
      f2a.lift_voltage_top: 400

