# Parameters for the curtis controller
/**:
  f2a_parameters_manager:
    ros__parameters:
      f2a.lift_scanner_threshold: 523
      f2a.lift_voltage_ground: 560
      f2a.lift_threshold_release: 10
