/**:
  ros__parameters:
    max_fork_height: 0.3 # from ground to fork bottom
    fork_lifted_threshold_m: 0.15
    max_fork_height_voltage: 853 #878 # When the fork is lowest
    empty_fork_lifted_threshold_m: 0.14 # from ground to fork bottom
    min_fork_height_voltage: 496 # When the fork is highest
