/**:
  ros__parameters:
    max_fork_height: 0.3 # from ground to fork bottom
    max_fork_height_voltage: 846  # When the fork is lowest
    min_fork_height_voltage: 498  # When the fork is highest
    fork_lifted_threshold_m: 0.18 # Copied default value to prevent xacro file crash
    lift_ground_threshold: 0.02 # fork on ground level threshold

