/**:
  ros__parameters:
    max_fork_height: 0.3 # from ground to fork bottom
    max_fork_height_voltage: 855.0  # When the fork is lowest
    min_fork_height_voltage: 501.6  # When the fork is highest
    fork_lifted_threshold_m: 0.19
    lift_ground_threshold: 0.02 # fork on ground level threshold

