/**:
  ros__parameters:
    max_fork_height: 0.3 # from ground to fork bottom
    fork_lifted_threshold_m: 0.18 # from ground to fork bottom
    max_fork_height_voltage: 980 # When the fork is lowest
    empty_fork_lifted_threshold_m: 0.14 # from ground to fork bottom
    min_fork_height_voltage: 80  # When the fork is highest
    max_velocity_joystick: 1.5 # m/s
    lift_ground_threshold: 0.02 # fork on ground level threshold
