max_speed_rps: 7.5 # max speed in rps (rotations per second = angular veloctiy)
max_fork_height: 0.3
max_fork_height_voltage: 880 # When the fork is lowest
min_fork_height_voltage: 120 # When the fork is highest

