/**:
  ros__parameters:
    max_fork_height: 0.3 # from ground to fork bottom
    fork_lifted_threshold_m: 0.15
    max_fork_height_voltage: 998 # When the fork is lowest
    min_fork_height_voltage: 120 # When the fork is highest
