/**:
  ros__parameters:
    max_fork_height: 0.3 # from ground to fork bottom
    fork_lifted_threshold_m: 0.19
    max_fork_height_voltage: 985 # When the fork is lowest
    min_fork_height_voltage: 166 # When the fork is highest
    lift_ground_threshold: 0.02 # fork on ground level threshold
