/**:
  ros__parameters:
    max_fork_height: 0.3 # from ground to fork bottom
    fork_lifted_threshold_m: 0.18 # from ground to fork bottom
    max_fork_height_voltage: 851  # When the fork is lowest
    empty_fork_lifted_threshold_m: 0.14 # from ground to fork bottom
    min_fork_height_voltage: 499 # When the fork is highest
    lift_ground_threshold: 0.02 # fork on ground level threshold
