/**:
  rosbag_recorder:
    ros__parameters:
      topics: # Without leading slash (/) if it is to be prepended with namespace (if namespace is used)
        [
          "points2/filtered",
          "global_costmap/costmap",
          "global_costmap/voxel_grid",
          "global_costmap/published_footprint",
          "global_plan",
          "goal_from_pallet_position",
          "w2mo_waypoints_to_goal",
          "paths_of_other_amrs",
          "cut_path_of_amr",
          "closest_free_pose_on_path",
          "initial_pallet_putdown_goal",
          "local_costmap/costmap",
          "local_costmap/published_footprint",
          "local_costmap/voxel_grid",
          "obstacle_aggregator/obstacles_marker",
          "obstacle_filter/filter_polygon",
          "obstacle_filter/obstacles_marker",
          "teb_markers",
          "teb_poses",
          "tf",
          "tf_static",
          "action_server_error_message",
          "cmd_vel",
          "teb_flickering_protection/cmd_vel",
          "velocity_smoother/cmd_vel",
          "collision_monitor/cmd_vel",
          "tricycle_controller/cmd_ackermann",
          "speed_limit",
          "odometry/filtered",
          "load_sensor_status",
          "/clock",
          "/rosout",
          "diagnostics",
          "diagnostics_agg",
          "diagnostics_toplevel_state",
          "battery_state",
          "backward_lidar",
          "forward_lidar",
          "emergency_button",
          "lidar_fieldset_conditions",
          "lidar_field",
          "sick_error",
          "interlock",
          "total_distance",
          "steering_controller_error",
          "traction_controller_error",
          "joy",
          "execute_goal_execute_goal_rclcpp_node/behavior_tree_log",
          "execute_goal/bt_info",
          "amr_navigate_to_pose_amr_navigate_to_pose_rclcpp_node/behavior_tree_log",
          "amr_navigate_to_pose/bt_info",
          "scanned_barcodes",
          "camera_localizations",
          "imu",
          "lift_height_sensor_voltage",
          "robot_description",
          "joint_states",
        ]