/**:
  pallet_transportation_action_servers:
    ros__parameters:
      side_offset: 0.4
      consider_fillgrade: true
      approach_goal_distance_meters: 1.5
      platform_approach_goal_offset: 1.4
      platform_marker_size: 0.11
      markers_to_w2mo_bin_distance: 0.6 # Positive if bin is behind markers (pre-approach goal adjustment)
      goal_offset_x: -1.5 # Markers to goal  ## Negative is deeper in the bin ### if changed also change pallet_putdown_to_platform.xml line 58
      goal_offset_y: 0.02 # Positive is to the right, when looking from AMR towards platform
      angular_goal_adjustment: 0.0  # Positive is counterclockwise
      lift_height_for_pickup: 0.11 # Fork lift level change to lift the pallet ## 14->18cm for the basement
      lift_height_for_driving_out: 0.21 # We lift the forks a bit higher when driving out of the platform

